language: d

d:
  - dmd-nightly
  - ldc-latest-ci

jobs:
  include:
    - name: "Linux DMD"
      os: linux
      dist: bionic
      d: dmd-nightly
    - name: "Mac DMD"
      os: osx
      osx_image: xcode11.3
      d: dmd-nightly
    - name: "Linux LDC"
      os: linux
      dist: bionic
      d: ldc-latest-ci
    - name: "Mac LDC"
      os: osx
      osx_image: xcode11.3
      d: ldc-latest-ci

script:
  - bash ./.travis.sh
